version: '3.8'

services:
  digital-transaction-db:
    image: postgres:16-alpine
    restart: always
    networks:
      - my-custom-network
    environment:
      POSTGRES_DB: digital-transaction-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - digital-transaction-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - my-custom-network
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypgadminpass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - digital-transaction-db

  digital-transaction-ms:
    hostname: digital-transaction-ms
    container_name: digital-transaction-ms
    networks:
      - my-custom-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8081"

volumes:
  digital-transaction-db-data:
  pgadmin_data:

networks:
  my-custom-network:
    driver: bridge